default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: holyday_development

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
